### ISSUE TITLE
数据集格式

### ISSUE THREAD

**Issue by liqianqi** [chenjunnn/rm_auto_aim#7]
您好，请问一下数据集的格式是什么？

**Comment by chenjunnn** [comment]
分类网络的输入是NCHW：1x1x28x20

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: liqianqi ***@***.***>
发送时间: Tuesday, August 9, 2022 4:37:05 PM
收件人: chenjunnn/rm_auto_aim ***@***.***>
抄送: Subscribed ***@***.***>
主题: [chenjunnn/rm_auto_aim] 数据集格式 (Issue #7)


您好，请问一下数据集的格式是什么？

―
